spring:
  application:
    name: card

  datasource:
    url: jdbc:h2:mem:carddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

# Eureka Client 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname:${random.value}}:${server.port:${random.int}}

# Feign Client 설정
feign:
  account:
    url: http://localhost:8081
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      account-service:
        connectTimeout: 3000
        readTimeout: 5000

# Logging 설정
logging:
  level:
    com.socoolheeya.bluebank.card: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE