{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blue-bank.serviceAccountName" . }}
  labels:
    {{- include "blue-bank.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
