apiVersion: v1
kind: Service
metadata:
  name: blue-bank-account
  namespace: blue-bank
spec:
  type: ClusterIP
  selector:
    app: blue-bank-account
  ports:
    - name: http
      port: 8100
      targetPort: http