apiVersion: v1
kind: Service
metadata:
  name: blue-bank-card
  namespace: blue-bank
spec:
  type: ClusterIP
  selector:
    app: blue-bank-card
  ports:
    - name: http
      port: 8400
      targetPort: http