apiVersion: v1
kind: Service
metadata:
  name: blue-bank-deposit
  namespace: blue-bank
spec:
  type: ClusterIP
  selector:
    app: blue-bank-deposit
  ports:
    - name: http
      port: 8200
      targetPort: http