apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
  namespace: blue-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      imagePullSecrets:
        - name: ncr-registry
      containers:
        - name: loan
          image: blue-bank-dev.kr.ncr.ntruss.com/loan:dev-9bda9c3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8300
          env:
            - name: SERVER_PORT
              value: "8300"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20