apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
images:
  - name: blue-bank-dev.kr.ncr.ntruss.com/account
    newName: blue-bank-dev.kr.ncr.ntruss.com/account
    newTag: dev-3ffba08fd956f3d9885c68b915de778b4f98b22f
  - name: blue-bank-dev.kr.ncr.ntruss.com/deposit
    newName: blue-bank-dev.kr.ncr.ntruss.com/deposit
    newTag: dev-3ffba08fd956f3d9885c68b915de778b4f98b22f
  - name: blue-bank-dev.kr.ncr.ntruss.com/loan
    newName: blue-bank-dev.kr.ncr.ntruss.com/loan
    newTag: dev-3ffba08fd956f3d9885c68b915de778b4f98b22f
  - name: blue-bank-dev.kr.ncr.ntruss.com/card
    newName: blue-bank-dev.kr.ncr.ntruss.com/card
    newTag: dev-3ffba08fd956f3d9885c68b915de778b4f98b22f